[package]
name = "gary"
version = "0.1.0"
authors = ["Marek Counts <mcounts@suse.com>"]
edition = "2018"

[[bin]]
name = "server"
path = "src/main.rs"

[features]

[dependencies]
clap = "2.33.0"
core = { path = "core"}
daemonize = "0.4.1"
log = "0.4.6"