[package]
name = "gary"
version = "0.1.0"
authors = ["Marek Counts <mcounts@suse.com>"]
edition = "2018"

[[bin]]
name = "server"
path = "src/main.rs"

[features]
default = ["build-nng"]
build-nng = ["nng-sys/build-nng"]
ffi-module = []

[dependencies]

