[package]
name = "gary-zmq"
version = "0.1.0"
authors = ["Marek Counts <mcounts@suse.com>"]
edition = "2018"

[dependencies]
zmq = "0.9"
core = { path = "../core"}

[features]
default = ['vendored-zmq']
vendored-zmq = ['zmq/vendored']
