[package]
name = "node_comm"
version = "0.1.0"
authors = ["Marek Counts <mcounts@suse.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_yaml = "0.8"

[dev-dependencies]
serde_derive = "1.0"
